package net.faulj.bench;

import net.faulj.decomposition.bidiagonal.Bidiagonalization;
import net.faulj.decomposition.result.BidiagonalizationResult;
import net.faulj.matrix.Matrix;
import net.faulj.matrix.MatrixUtils;
import net.faulj.nativeblas.BackendRegistry;
import net.faulj.nativeblas.BackendSnapshot;

import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Compare Java and C++ bidiagonal backends across shape families and write calibrated dispatch buckets.
 */
public final class BidiagonalBackendComparisonRunner {
    private BidiagonalBackendComparisonRunner() {
    }

    public static void main(String[] args) {
        BackendComparisonSupport.Shape[] shapes = new BackendComparisonSupport.Shape[] {
            new BackendComparisonSupport.Shape(64, 64),
            new BackendComparisonSupport.Shape(96, 96),
            new BackendComparisonSupport.Shape(128, 128),
            new BackendComparisonSupport.Shape(192, 128),
            new BackendComparisonSupport.Shape(128, 192),
            new BackendComparisonSupport.Shape(256, 192),
            new BackendComparisonSupport.Shape(192, 256),
            new BackendComparisonSupport.Shape(384, 256),
            new BackendComparisonSupport.Shape(256, 384),
            new BackendComparisonSupport.Shape(512, 384)
        };
        int warmupRuns = 2;
        int measuredRuns = 3;
        Path calibrationOut = null;

        for (String arg : args) {
            if (arg == null) {
                continue;
            }
            if (arg.startsWith("--sizes=")) {
                shapes = BackendComparisonSupport.squareShapes(
                    BackendComparisonSupport.parseSizes(arg.substring("--sizes=".length()),
                        BackendComparisonSupport.extractSquareSizes(shapes)));
            } else if (arg.startsWith("--shapes=")) {
                shapes = BackendComparisonSupport.parseShapes(arg.substring("--shapes=".length()), shapes);
            } else if (arg.startsWith("--warmup=")) {
                warmupRuns = BackendComparisonSupport.parsePositiveInt(arg.substring("--warmup=".length()), warmupRuns);
            } else if (arg.startsWith("--runs=")) {
                measuredRuns = BackendComparisonSupport.parsePositiveInt(arg.substring("--runs=".length()), measuredRuns);
            } else if (arg.startsWith("--calibrationOut=")) {
                calibrationOut = BackendComparisonSupport.parseCalibrationOut(
                    arg.substring("--calibrationOut=".length()).trim());
            }
        }

        System.out.println("BIDIAGONAL_BACKEND_COMPARISON");
        System.out.println("mode=decompose");
        System.out.println("warmupRuns=" + warmupRuns);
        System.out.println("measuredRuns=" + measuredRuns);

        Map<String, String> suggestedProperties = new LinkedHashMap<>();
        for (BackendComparisonSupport.Shape shape : shapes) {
            Matrix a = BackendComparisonSupport.randomMatrix(shape.rows(), shape.cols(),
                11_000L + shape.rows() * 1_000L + shape.cols());
            BackendComparisonSupport.Result javaResult = runBackend("java", a, warmupRuns, measuredRuns);
            BackendComparisonSupport.Result cppResult = runBackend("cpp", a, warmupRuns, measuredRuns);
            BackendComparisonSupport.addCalibrationProperties(suggestedProperties, "bidiagonal", "decompose",
                shape, javaResult, cppResult, measuredRuns);

            System.out.printf(Locale.ROOT, "shape=%dx%d family=%s bandMetric=%d%n",
                shape.rows(), shape.cols(), shape.family().propertyKey(), shape.problemSize());
            BackendComparisonSupport.printResult("java", javaResult);
            BackendComparisonSupport.printResult("cpp", cppResult);
            System.out.println("winner=" + (javaResult.bestSeconds() <= cppResult.bestSeconds() ? "java" : "cpp"));
            System.out.println("cpp_correctness=" + (cppResult.correctnessPass() ? "PASS" : "FAIL"));
            System.out.printf(Locale.ROOT, "cpp_residual=%.6e%n", cppResult.residual());
            System.out.printf(Locale.ROOT, "cpp_orthogonality=%.6e%n", cppResult.orthogonality());
        }

        if (calibrationOut != null) {
            BackendComparisonSupport.writeCalibrationFile(calibrationOut, suggestedProperties,
                "bidiagonal", "decompose", warmupRuns, measuredRuns, shapes,
                "Algorithm dispatch calibration generated by BidiagonalBackendComparisonRunner");
            System.out.println("calibration_written=" + calibrationOut.toAbsolutePath());
        }
    }

    private static BackendComparisonSupport.Result runBackend(String backend, Matrix a, int warmupRuns, int measuredRuns) {
        System.setProperty("jlc.backend", "cpp".equals(backend) ? "native" : "java");
        System.setProperty("jlc.algorithm.bidiagonal.backend", backend);

        Bidiagonalization decomposition = new Bidiagonalization();
        for (int i = 0; i < warmupRuns; i++) {
            decomposition.decompose(a);
        }

        double flops = bidiagonalFlops(a.getRowCount(), a.getColumnCount());
        double best = Double.POSITIVE_INFINITY;
        double total = 0.0;
        for (int i = 0; i < measuredRuns; i++) {
            long start = System.nanoTime();
            decomposition.decompose(a);
            double seconds = (System.nanoTime() - start) / 1e9;
            best = Math.min(best, seconds);
            total += seconds;
        }

        BackendSnapshot snapshot = BackendRegistry.snapshot();
        BackendComparisonSupport.Correctness correctness = "cpp".equals(backend)
            ? validateCpp(a)
            : new BackendComparisonSupport.Correctness(true, Double.NaN, Double.NaN);
        return new BackendComparisonSupport.Result(snapshot, best, total / measuredRuns, flops,
            correctness.pass(), correctness.residual(), correctness.orthogonality());
    }

    private static BackendComparisonSupport.Correctness validateCpp(Matrix a) {
        try {
            System.setProperty("jlc.algorithm.bidiagonal.backend", "java");
            BidiagonalizationResult javaResult = new Bidiagonalization().decompose(a);
            System.setProperty("jlc.algorithm.bidiagonal.backend", "cpp");
            BidiagonalizationResult cppResult = new Bidiagonalization().decompose(a);
            double residual = cppResult.residualNorm();
            double orthogonality = Math.max(
                MatrixUtils.orthogonalityError(cppResult.getU()),
                MatrixUtils.orthogonalityError(cppResult.getV()));
            boolean pass = residual < 1e-8
                && orthogonality < 1e-8
                && BackendComparisonSupport.relativeDifference(javaResult.reconstruct(), cppResult.reconstruct()) < 1e-8;
            return new BackendComparisonSupport.Correctness(pass, residual, orthogonality);
        } catch (RuntimeException | LinkageError ignored) {
            return BackendComparisonSupport.Correctness.failed();
        }
    }

    private static double bidiagonalFlops(int rows, int cols) {
        int m = Math.max(rows, cols);
        int n = Math.min(rows, cols);
        return 4.0 * m * (double) n * n - (4.0 / 3.0) * n * n * n;
    }
}
