package net.faulj.bench;

import net.faulj.decomposition.hessenberg.HessenbergReduction;
import net.faulj.decomposition.result.HessenbergResult;
import net.faulj.matrix.Matrix;
import net.faulj.matrix.MatrixUtils;
import net.faulj.nativeblas.BackendRegistry;
import net.faulj.nativeblas.BackendSnapshot;

import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Compare Java and C++ Hessenberg backends across square sizes and write calibrated dispatch buckets.
 */
public final class HessenbergBackendComparisonRunner {
    private HessenbergBackendComparisonRunner() {
    }

    public static void main(String[] args) {
        BackendComparisonSupport.Shape[] shapes = BackendComparisonSupport.squareShapes(
            new int[] {32, 48, 64, 96, 128, 160, 192, 256, 384, 512, 768, 1024});
        int warmupRuns = 2;
        int measuredRuns = 3;
        Mode mode = Mode.DECOMPOSE;
        Path calibrationOut = null;

        for (String arg : args) {
            if (arg == null) {
                continue;
            }
            if (arg.startsWith("--sizes=")) {
                shapes = BackendComparisonSupport.squareShapes(
                    BackendComparisonSupport.parseSizes(arg.substring("--sizes=".length()),
                        BackendComparisonSupport.extractSquareSizes(shapes)));
            } else if (arg.startsWith("--warmup=")) {
                warmupRuns = BackendComparisonSupport.parsePositiveInt(arg.substring("--warmup=".length()), warmupRuns);
            } else if (arg.startsWith("--runs=")) {
                measuredRuns = BackendComparisonSupport.parsePositiveInt(arg.substring("--runs=".length()), measuredRuns);
            } else if (arg.startsWith("--mode=")) {
                mode = Mode.parse(arg.substring("--mode=".length()));
            } else if (arg.startsWith("--calibrationOut=")) {
                calibrationOut = BackendComparisonSupport.parseCalibrationOut(
                    arg.substring("--calibrationOut=".length()).trim());
            }
        }

        System.out.println("HESSENBERG_BACKEND_COMPARISON");
        System.out.println("mode=" + mode.cliName);
        System.out.println("warmupRuns=" + warmupRuns);
        System.out.println("measuredRuns=" + measuredRuns);

        Map<String, String> suggestedProperties = new LinkedHashMap<>();
        for (BackendComparisonSupport.Shape shape : shapes) {
            Matrix a = BackendComparisonSupport.randomMatrix(shape.rows(), shape.cols(), 9000L + shape.rows());
            BackendComparisonSupport.Result javaResult = runBackend("java", a, mode, warmupRuns, measuredRuns);
            BackendComparisonSupport.Result cppResult = runBackend("cpp", a, mode, warmupRuns, measuredRuns);
            BackendComparisonSupport.addCalibrationProperties(suggestedProperties, "hessenberg", mode.dispatchMode,
                shape, javaResult, cppResult, measuredRuns);

            System.out.printf(Locale.ROOT, "shape=%dx%d family=%s bandMetric=%d%n",
                shape.rows(), shape.cols(), shape.family().propertyKey(), shape.problemSize());
            BackendComparisonSupport.printResult("java", javaResult);
            BackendComparisonSupport.printResult("cpp", cppResult);
            System.out.println("winner=" + (javaResult.bestSeconds() <= cppResult.bestSeconds() ? "java" : "cpp"));
            System.out.println("cpp_correctness=" + (cppResult.correctnessPass() ? "PASS" : "FAIL"));
            System.out.printf(Locale.ROOT, "cpp_residual=%.6e%n", cppResult.residual());
            if (Double.isFinite(cppResult.orthogonality())) {
                System.out.printf(Locale.ROOT, "cpp_orthogonality=%.6e%n", cppResult.orthogonality());
            }
        }

        if (calibrationOut != null) {
            BackendComparisonSupport.writeCalibrationFile(calibrationOut, suggestedProperties,
                "hessenberg", mode.dispatchMode, warmupRuns, measuredRuns, shapes,
                "Algorithm dispatch calibration generated by HessenbergBackendComparisonRunner");
            System.out.println("calibration_written=" + calibrationOut.toAbsolutePath());
        }
    }

    private static BackendComparisonSupport.Result runBackend(String backend, Matrix a, Mode mode,
                                                              int warmupRuns, int measuredRuns) {
        System.setProperty("jlc.backend", "cpp".equals(backend) ? "native" : "java");
        System.setProperty("jlc.algorithm.hessenberg.backend", backend);

        for (int i = 0; i < warmupRuns; i++) {
            execute(a, mode);
        }

        double n = a.getRowCount();
        double flops = (10.0 / 3.0) * n * n * n;
        double best = Double.POSITIVE_INFINITY;
        double total = 0.0;
        for (int i = 0; i < measuredRuns; i++) {
            long start = System.nanoTime();
            execute(a, mode);
            double seconds = (System.nanoTime() - start) / 1e9;
            best = Math.min(best, seconds);
            total += seconds;
        }

        BackendSnapshot snapshot = BackendRegistry.snapshot();
        BackendComparisonSupport.Correctness correctness = "cpp".equals(backend)
            ? validateCpp(a, mode)
            : new BackendComparisonSupport.Correctness(true, Double.NaN, Double.NaN);
        return new BackendComparisonSupport.Result(snapshot, best, total / measuredRuns, flops,
            correctness.pass(), correctness.residual(), correctness.orthogonality());
    }

    private static void execute(Matrix a, Mode mode) {
        if (mode == Mode.REDUCE) {
            HessenbergReduction.reduceToHessenberg(a);
        } else {
            HessenbergReduction.decompose(a);
        }
    }

    private static BackendComparisonSupport.Correctness validateCpp(Matrix a, Mode mode) {
        try {
            System.setProperty("jlc.algorithm.hessenberg.backend", "java");
            if (mode == Mode.REDUCE) {
                Matrix javaResult = HessenbergReduction.reduceToHessenberg(a);
                System.setProperty("jlc.algorithm.hessenberg.backend", "cpp");
                Matrix cppResult = HessenbergReduction.reduceToHessenberg(a);
                double residual = BackendComparisonSupport.relativeDifference(javaResult, cppResult);
                boolean pass = residual < 1e-8 && hasHessenbergStructure(cppResult);
                return new BackendComparisonSupport.Correctness(pass, residual, Double.NaN);
            }

            HessenbergResult javaResult = HessenbergReduction.decompose(a);
            System.setProperty("jlc.algorithm.hessenberg.backend", "cpp");
            HessenbergResult cppResult = HessenbergReduction.decompose(a);
            double residual = cppResult.residualNorm();
            double orthogonality = MatrixUtils.orthogonalityError(cppResult.getQ());
            boolean pass = residual < 1e-8
                && orthogonality < 1e-8
                && BackendComparisonSupport.relativeDifference(javaResult.getH(), cppResult.getH()) < 1e-8
                && BackendComparisonSupport.relativeDifference(javaResult.getQ(), cppResult.getQ()) < 1e-8
                && hasHessenbergStructure(cppResult.getH());
            return new BackendComparisonSupport.Correctness(pass, residual, orthogonality);
        } catch (RuntimeException | LinkageError ignored) {
            return BackendComparisonSupport.Correctness.failed();
        }
    }

    private static boolean hasHessenbergStructure(Matrix h) {
        for (int row = 2; row < h.getRowCount(); row++) {
            for (int col = 0; col < row - 1; col++) {
                if (Math.abs(h.get(row, col)) > 1e-8) {
                    return false;
                }
            }
        }
        return true;
    }

    private enum Mode {
        REDUCE("reduce"),
        DECOMPOSE("decompose");

        private final String cliName;
        private final String dispatchMode;

        Mode(String cliName) {
            this.cliName = cliName;
            this.dispatchMode = cliName;
        }

        static Mode parse(String value) {
            if (value == null) {
                return DECOMPOSE;
            }
            return switch (value.trim().toLowerCase(Locale.ROOT)) {
                case "reduce" -> REDUCE;
                default -> DECOMPOSE;
            };
        }
    }
}
