package net.faulj.bench;

import net.faulj.decomposition.lu.LUDecomposition;
import net.faulj.decomposition.result.LUResult;
import net.faulj.matrix.Matrix;
import net.faulj.nativeblas.BackendRegistry;
import net.faulj.nativeblas.BackendSnapshot;

import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Compare Java and C++ LU backends across square sizes and write calibrated dispatch buckets.
 */
public final class LuBackendComparisonRunner {
    private LuBackendComparisonRunner() {
    }

    public static void main(String[] args) {
        BackendComparisonSupport.Shape[] shapes = BackendComparisonSupport.squareShapes(
            new int[] {32, 48, 64, 96, 128, 160, 192, 256, 384, 512, 768, 1024});
        int warmupRuns = 2;
        int measuredRuns = 3;
        Path calibrationOut = null;

        for (String arg : args) {
            if (arg == null) {
                continue;
            }
            if (arg.startsWith("--sizes=")) {
                shapes = BackendComparisonSupport.squareShapes(
                    BackendComparisonSupport.parseSizes(arg.substring("--sizes=".length()),
                        BackendComparisonSupport.extractSquareSizes(shapes)));
            } else if (arg.startsWith("--warmup=")) {
                warmupRuns = BackendComparisonSupport.parsePositiveInt(arg.substring("--warmup=".length()), warmupRuns);
            } else if (arg.startsWith("--runs=")) {
                measuredRuns = BackendComparisonSupport.parsePositiveInt(arg.substring("--runs=".length()), measuredRuns);
            } else if (arg.startsWith("--calibrationOut=")) {
                calibrationOut = BackendComparisonSupport.parseCalibrationOut(
                    arg.substring("--calibrationOut=".length()).trim());
            }
        }

        System.out.println("LU_BACKEND_COMPARISON");
        System.out.println("mode=factor");
        System.out.println("warmupRuns=" + warmupRuns);
        System.out.println("measuredRuns=" + measuredRuns);

        Map<String, String> suggestedProperties = new LinkedHashMap<>();
        for (BackendComparisonSupport.Shape shape : shapes) {
            Matrix a = BackendComparisonSupport.randomDiagonallyDominant(shape.rows(), 5000L + shape.rows());
            BackendComparisonSupport.Result javaResult = runBackend("java", a, warmupRuns, measuredRuns);
            BackendComparisonSupport.Result cppResult = runBackend("cpp", a, warmupRuns, measuredRuns);
            BackendComparisonSupport.addCalibrationProperties(suggestedProperties, "lu", "factor",
                shape, javaResult, cppResult, measuredRuns);

            System.out.printf(Locale.ROOT, "shape=%dx%d family=%s bandMetric=%d%n",
                shape.rows(), shape.cols(), shape.family().propertyKey(), shape.problemSize());
            BackendComparisonSupport.printResult("java", javaResult);
            BackendComparisonSupport.printResult("cpp", cppResult);
            System.out.println("winner=" + (javaResult.bestSeconds() <= cppResult.bestSeconds() ? "java" : "cpp"));
            System.out.println("cpp_correctness=" + (cppResult.correctnessPass() ? "PASS" : "FAIL"));
            System.out.printf(Locale.ROOT, "cpp_residual=%.6e%n", cppResult.residual());
        }

        if (calibrationOut != null) {
            BackendComparisonSupport.writeCalibrationFile(calibrationOut, suggestedProperties,
                "lu", "factor", warmupRuns, measuredRuns, shapes,
                "Algorithm dispatch calibration generated by LuBackendComparisonRunner");
            System.out.println("calibration_written=" + calibrationOut.toAbsolutePath());
        }
    }

    private static BackendComparisonSupport.Result runBackend(String backend, Matrix a, int warmupRuns, int measuredRuns) {
        System.setProperty("jlc.backend", "cpp".equals(backend) ? "native" : "java");
        System.setProperty("jlc.algorithm.lu.backend", backend);

        LUDecomposition decomposition = new LUDecomposition();
        for (int i = 0; i < warmupRuns; i++) {
            decomposition.decompose(a);
        }

        double flops = (2.0 / 3.0) * a.getRowCount() * (double) a.getRowCount() * a.getRowCount();
        double best = Double.POSITIVE_INFINITY;
        double total = 0.0;
        for (int i = 0; i < measuredRuns; i++) {
            long start = System.nanoTime();
            decomposition.decompose(a);
            double seconds = (System.nanoTime() - start) / 1e9;
            best = Math.min(best, seconds);
            total += seconds;
        }

        BackendSnapshot snapshot = BackendRegistry.snapshot();
        BackendComparisonSupport.Correctness correctness = "cpp".equals(backend)
            ? validateCpp(a)
            : new BackendComparisonSupport.Correctness(true, Double.NaN, Double.NaN);
        return new BackendComparisonSupport.Result(snapshot, best, total / measuredRuns, flops,
            correctness.pass(), correctness.residual(), correctness.orthogonality());
    }

    private static BackendComparisonSupport.Correctness validateCpp(Matrix a) {
        try {
            System.setProperty("jlc.algorithm.lu.backend", "java");
            LUResult javaResult = new LUDecomposition().decompose(a);
            System.setProperty("jlc.algorithm.lu.backend", "cpp");
            LUResult cppResult = new LUDecomposition().decompose(a);
            boolean permutationPass = javaResult.getP().size() == cppResult.getP().size();
            for (int i = 0; permutationPass && i < javaResult.getP().size(); i++) {
                permutationPass = javaResult.getP().get(i) == cppResult.getP().get(i);
            }
            double residual = cppResult.residualNorm();
            boolean pass = !cppResult.isSingular()
                && residual < 1e-10
                && BackendComparisonSupport.relativeDifference(javaResult.getL(), cppResult.getL()) < 1e-10
                && BackendComparisonSupport.relativeDifference(javaResult.getU(), cppResult.getU()) < 1e-10
                && permutationPass;
            return new BackendComparisonSupport.Correctness(pass, residual, Double.NaN);
        } catch (RuntimeException | LinkageError ignored) {
            return BackendComparisonSupport.Correctness.failed();
        }
    }
}
