package net.faulj.bench;

import net.faulj.decomposition.result.SchurResult;
import net.faulj.eigen.schur.RealSchurDecomposition;
import net.faulj.matrix.Matrix;
import net.faulj.matrix.MatrixUtils;
import net.faulj.nativeblas.BackendRegistry;
import net.faulj.nativeblas.BackendSnapshot;

import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Compare Java and C++ native-assisted Schur backends across square sizes.
 */
public final class SchurBackendComparisonRunner {
    private SchurBackendComparisonRunner() {
    }

    public static void main(String[] args) {
        BackendComparisonSupport.Shape[] shapes = BackendComparisonSupport.squareShapes(
            new int[] {32, 48, 64, 96, 128, 192, 256});
        int warmupRuns = 1;
        int measuredRuns = 2;
        Mode mode = Mode.DECOMPOSE;
        Path calibrationOut = null;

        for (String arg : args) {
            if (arg == null) {
                continue;
            }
            if (arg.startsWith("--sizes=")) {
                shapes = BackendComparisonSupport.squareShapes(
                    BackendComparisonSupport.parseSizes(arg.substring("--sizes=".length()),
                        BackendComparisonSupport.extractSquareSizes(shapes)));
            } else if (arg.startsWith("--warmup=")) {
                warmupRuns = BackendComparisonSupport.parsePositiveInt(arg.substring("--warmup=".length()), warmupRuns);
            } else if (arg.startsWith("--runs=")) {
                measuredRuns = BackendComparisonSupport.parsePositiveInt(arg.substring("--runs=".length()), measuredRuns);
            } else if (arg.startsWith("--mode=")) {
                mode = Mode.parse(arg.substring("--mode=".length()));
            } else if (arg.startsWith("--calibrationOut=")) {
                calibrationOut = BackendComparisonSupport.parseCalibrationOut(
                    arg.substring("--calibrationOut=".length()).trim());
            }
        }

        System.out.println("SCHUR_BACKEND_COMPARISON");
        System.out.println("mode=" + mode.cliName);
        System.out.println("warmupRuns=" + warmupRuns);
        System.out.println("measuredRuns=" + measuredRuns);

        Map<String, String> suggestedProperties = new LinkedHashMap<>();
        for (BackendComparisonSupport.Shape shape : shapes) {
            Matrix a = BackendComparisonSupport.randomMatrix(shape.rows(), shape.cols(), 15_000L + shape.rows());
            BackendComparisonSupport.Result javaResult = runBackend("java", a, mode, warmupRuns, measuredRuns);
            BackendComparisonSupport.Result cppResult = runBackend("cpp", a, mode, warmupRuns, measuredRuns);
            BackendComparisonSupport.addCalibrationProperties(suggestedProperties, "schur", mode.dispatchMode,
                shape, javaResult, cppResult, measuredRuns);

            System.out.printf(Locale.ROOT, "shape=%dx%d family=%s bandMetric=%d%n",
                shape.rows(), shape.cols(), shape.family().propertyKey(), shape.problemSize());
            BackendComparisonSupport.printResult("java", javaResult);
            BackendComparisonSupport.printResult("cpp", cppResult);
            System.out.println("winner=" + (javaResult.bestSeconds() <= cppResult.bestSeconds() ? "java" : "cpp"));
            System.out.println("cpp_correctness=" + (cppResult.correctnessPass() ? "PASS" : "FAIL"));
            System.out.printf(Locale.ROOT, "cpp_residual=%.6e%n", cppResult.residual());
            if (Double.isFinite(cppResult.orthogonality())) {
                System.out.printf(Locale.ROOT, "cpp_orthogonality=%.6e%n", cppResult.orthogonality());
            }
        }

        if (calibrationOut != null) {
            BackendComparisonSupport.writeCalibrationFile(calibrationOut, suggestedProperties,
                "schur", mode.dispatchMode, warmupRuns, measuredRuns, shapes,
                "Algorithm dispatch calibration generated by SchurBackendComparisonRunner");
            System.out.println("calibration_written=" + calibrationOut.toAbsolutePath());
        }
    }

    private static BackendComparisonSupport.Result runBackend(String backend, Matrix a, Mode mode,
                                                              int warmupRuns, int measuredRuns) {
        System.setProperty("jlc.backend", "cpp".equals(backend) ? "native" : "java");
        System.setProperty("jlc.algorithm.schur.backend", backend);

        for (int i = 0; i < warmupRuns; i++) {
            execute(a, mode);
        }

        double n = a.getRowCount();
        double flops = 15.0 * n * n * n;
        double best = Double.POSITIVE_INFINITY;
        double total = 0.0;
        for (int i = 0; i < measuredRuns; i++) {
            long start = System.nanoTime();
            execute(a, mode);
            double seconds = (System.nanoTime() - start) / 1e9;
            best = Math.min(best, seconds);
            total += seconds;
        }

        BackendSnapshot snapshot = BackendRegistry.snapshot();
        BackendComparisonSupport.Correctness correctness = "cpp".equals(backend)
            ? validateCpp(a, mode)
            : new BackendComparisonSupport.Correctness(true, Double.NaN, Double.NaN);
        return new BackendComparisonSupport.Result(snapshot, best, total / measuredRuns, flops,
            correctness.pass(), correctness.residual(), correctness.orthogonality());
    }

    private static Object execute(Matrix a, Mode mode) {
        return mode == Mode.SCHUR_FORM_ONLY ? RealSchurDecomposition.schurT(a) : RealSchurDecomposition.decompose(a);
    }

    private static BackendComparisonSupport.Correctness validateCpp(Matrix a, Mode mode) {
        try {
            System.setProperty("jlc.algorithm.schur.backend", "java");
            Object javaResult = execute(a, mode);
            System.setProperty("jlc.algorithm.schur.backend", "cpp");
            Object cppResult = execute(a, mode);
            if (mode == Mode.SCHUR_FORM_ONLY) {
                Matrix javaT = (Matrix) javaResult;
                Matrix cppT = (Matrix) cppResult;
                double residual = BackendComparisonSupport.relativeDifference(javaT, cppT);
                boolean pass = residual < 1e-8 && isQuasiUpperTriangular(cppT);
                return new BackendComparisonSupport.Correctness(pass, residual, Double.NaN);
            }

            SchurResult javaSchur = (SchurResult) javaResult;
            SchurResult cppSchur = (SchurResult) cppResult;
            double residual = cppSchur.residualNorm();
            double orthogonality = MatrixUtils.orthogonalityError(cppSchur.getU());
            boolean pass = residual < 1e-8
                && orthogonality < 1e-8
                && BackendComparisonSupport.relativeDifference(javaSchur.getT(), cppSchur.getT()) < 1e-8
                && BackendComparisonSupport.relativeDifference(javaSchur.getU(), cppSchur.getU()) < 1e-8
                && isQuasiUpperTriangular(cppSchur.getT());
            return new BackendComparisonSupport.Correctness(pass, residual, orthogonality);
        } catch (RuntimeException | LinkageError ignored) {
            return BackendComparisonSupport.Correctness.failed();
        }
    }

    private static boolean isQuasiUpperTriangular(Matrix t) {
        for (int row = 2; row < t.getRowCount(); row++) {
            for (int col = 0; col < row - 1; col++) {
                if (Math.abs(t.get(row, col)) > 1e-8) {
                    return false;
                }
            }
        }
        return true;
    }

    private enum Mode {
        DECOMPOSE("decompose"),
        SCHUR_FORM_ONLY("schur_form_only");

        private final String cliName;
        private final String dispatchMode;

        Mode(String cliName) {
            this.cliName = cliName;
            this.dispatchMode = cliName;
        }

        static Mode parse(String value) {
            if (value == null) {
                return DECOMPOSE;
            }
            return switch (value.trim().toLowerCase(Locale.ROOT)) {
                case "schur_form_only", "t_only", "t" -> SCHUR_FORM_ONLY;
                default -> DECOMPOSE;
            };
        }
    }
}
