package net.faulj.bench;

import net.faulj.decomposition.result.SVDResult;
import net.faulj.matrix.Matrix;
import net.faulj.matrix.MatrixUtils;
import net.faulj.nativeblas.BackendRegistry;
import net.faulj.nativeblas.BackendSnapshot;
import net.faulj.svd.SVDecomposition;
import net.faulj.svd.ThinSVD;

import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Compare Java and C++ native-assisted SVD backends across shape families.
 */
public final class SvdBackendComparisonRunner {
    private SvdBackendComparisonRunner() {
    }

    public static void main(String[] args) {
        BackendComparisonSupport.Shape[] shapes = new BackendComparisonSupport.Shape[] {
            new BackendComparisonSupport.Shape(64, 64),
            new BackendComparisonSupport.Shape(96, 64),
            new BackendComparisonSupport.Shape(64, 96),
            new BackendComparisonSupport.Shape(128, 96),
            new BackendComparisonSupport.Shape(96, 128),
            new BackendComparisonSupport.Shape(256, 256)
        };
        int warmupRuns = 1;
        int measuredRuns = 2;
        Mode mode = Mode.FULL;
        Path calibrationOut = null;

        for (String arg : args) {
            if (arg == null) {
                continue;
            }
            if (arg.startsWith("--sizes=")) {
                shapes = BackendComparisonSupport.squareShapes(
                    BackendComparisonSupport.parseSizes(arg.substring("--sizes=".length()),
                        BackendComparisonSupport.extractSquareSizes(shapes)));
            } else if (arg.startsWith("--shapes=")) {
                shapes = BackendComparisonSupport.parseShapes(arg.substring("--shapes=".length()), shapes);
            } else if (arg.startsWith("--warmup=")) {
                warmupRuns = BackendComparisonSupport.parsePositiveInt(arg.substring("--warmup=".length()), warmupRuns);
            } else if (arg.startsWith("--runs=")) {
                measuredRuns = BackendComparisonSupport.parsePositiveInt(arg.substring("--runs=".length()), measuredRuns);
            } else if (arg.startsWith("--mode=")) {
                mode = Mode.parse(arg.substring("--mode=".length()));
            } else if (arg.startsWith("--calibrationOut=")) {
                calibrationOut = BackendComparisonSupport.parseCalibrationOut(
                    arg.substring("--calibrationOut=".length()).trim());
            }
        }

        System.out.println("SVD_BACKEND_COMPARISON");
        System.out.println("mode=" + mode.cliName);
        System.out.println("warmupRuns=" + warmupRuns);
        System.out.println("measuredRuns=" + measuredRuns);

        Map<String, String> suggestedProperties = new LinkedHashMap<>();
        for (BackendComparisonSupport.Shape shape : shapes) {
            Matrix a = BackendComparisonSupport.randomMatrix(shape.rows(), shape.cols(),
                13_000L + shape.rows() * 1_000L + shape.cols());
            BackendComparisonSupport.Result javaResult = runBackend("java", a, mode, warmupRuns, measuredRuns);
            BackendComparisonSupport.Result cppResult = runBackend("cpp", a, mode, warmupRuns, measuredRuns);
            BackendComparisonSupport.addCalibrationProperties(suggestedProperties, "svd", mode.dispatchMode,
                shape, javaResult, cppResult, measuredRuns);

            System.out.printf(Locale.ROOT, "shape=%dx%d family=%s bandMetric=%d%n",
                shape.rows(), shape.cols(), shape.family().propertyKey(), shape.problemSize());
            BackendComparisonSupport.printResult("java", javaResult);
            BackendComparisonSupport.printResult("cpp", cppResult);
            System.out.println("winner=" + (javaResult.bestSeconds() <= cppResult.bestSeconds() ? "java" : "cpp"));
            System.out.println("cpp_correctness=" + (cppResult.correctnessPass() ? "PASS" : "FAIL"));
            System.out.printf(Locale.ROOT, "cpp_residual=%.6e%n", cppResult.residual());
            System.out.printf(Locale.ROOT, "cpp_orthogonality=%.6e%n", cppResult.orthogonality());
        }

        if (calibrationOut != null) {
            BackendComparisonSupport.writeCalibrationFile(calibrationOut, suggestedProperties,
                "svd", mode.dispatchMode, warmupRuns, measuredRuns, shapes,
                "Algorithm dispatch calibration generated by SvdBackendComparisonRunner");
            System.out.println("calibration_written=" + calibrationOut.toAbsolutePath());
        }
    }

    private static BackendComparisonSupport.Result runBackend(String backend, Matrix a, Mode mode,
                                                              int warmupRuns, int measuredRuns) {
        System.setProperty("jlc.backend", "cpp".equals(backend) ? "native" : "java");
        System.setProperty("jlc.algorithm.svd.backend", backend);

        for (int i = 0; i < warmupRuns; i++) {
            execute(a, mode);
        }

        double flops = svdFlops(a.getRowCount(), a.getColumnCount());
        double best = Double.POSITIVE_INFINITY;
        double total = 0.0;
        for (int i = 0; i < measuredRuns; i++) {
            long start = System.nanoTime();
            execute(a, mode);
            double seconds = (System.nanoTime() - start) / 1e9;
            best = Math.min(best, seconds);
            total += seconds;
        }

        BackendSnapshot snapshot = BackendRegistry.snapshot();
        BackendComparisonSupport.Correctness correctness = "cpp".equals(backend)
            ? validateCpp(a, mode)
            : new BackendComparisonSupport.Correctness(true, Double.NaN, Double.NaN);
        return new BackendComparisonSupport.Result(snapshot, best, total / measuredRuns, flops,
            correctness.pass(), correctness.residual(), correctness.orthogonality());
    }

    private static SVDResult execute(Matrix a, Mode mode) {
        return mode == Mode.THIN ? new ThinSVD().decompose(a) : new SVDecomposition().decompose(a);
    }

    private static BackendComparisonSupport.Correctness validateCpp(Matrix a, Mode mode) {
        try {
            System.setProperty("jlc.algorithm.svd.backend", "java");
            SVDResult javaResult = execute(a, mode);
            System.setProperty("jlc.algorithm.svd.backend", "cpp");
            SVDResult cppResult = execute(a, mode);
            double residual = BackendComparisonSupport.relativeDifference(javaResult.reconstruct(), cppResult.reconstruct());
            double orthogonality = Math.max(
                MatrixUtils.orthogonalityError(cppResult.getU()),
                MatrixUtils.orthogonalityError(cppResult.getV()));
            boolean pass = residual < 1e-8
                && orthogonality < 1e-8
                && singularValuesClose(javaResult.getSingularValues(), cppResult.getSingularValues(), 1e-8);
            return new BackendComparisonSupport.Correctness(pass, residual, orthogonality);
        } catch (RuntimeException | LinkageError ignored) {
            return BackendComparisonSupport.Correctness.failed();
        }
    }

    private static boolean singularValuesClose(double[] left, double[] right, double tolerance) {
        int len = Math.min(left.length, right.length);
        double diff = 0.0;
        double ref = 0.0;
        for (int i = 0; i < len; i++) {
            double delta = left[i] - right[i];
            diff = Math.fma(delta, delta, diff);
            ref = Math.fma(left[i], left[i], ref);
        }
        return Math.sqrt(diff) / Math.max(1.0, Math.sqrt(ref)) < tolerance;
    }

    private static double svdFlops(int rows, int cols) {
        int m = Math.max(rows, cols);
        int n = Math.min(rows, cols);
        return 4.0 * m * (double) n * n + 8.0 * n * (double) n * n;
    }

    private enum Mode {
        FULL("full"),
        THIN("thin");

        private final String cliName;
        private final String dispatchMode;

        Mode(String cliName) {
            this.cliName = cliName;
            this.dispatchMode = cliName;
        }

        static Mode parse(String value) {
            if (value == null) {
                return FULL;
            }
            return switch (value.trim().toLowerCase(Locale.ROOT)) {
                case "thin" -> THIN;
                default -> FULL;
            };
        }
    }
}
