package net.faulj.svd;

import net.faulj.matrix.Matrix;

/**
 * Utilities for estimating the numerical rank of a matrix.
 * <p>
 * The rank of a matrix is the dimension of the vector space generated by its columns.
 * In numerical linear algebra, this is determined by counting the number of singular
 * values strictly greater than a specific tolerance.
 * </p>
 *
 * <h2>Numerical Rank Definition:</h2>
 * <p>
 * The rank <i>r</i> is the number of singular values σ<sub>i</sub> such that:
 * </p>
 * <pre>
 * σ<sub>i</sub> > ε
 * </pre>
 * <p>
 * Where ε is a tolerance threshold accounting for floating-point errors.
 * </p>
 *
 * <h2>Tolerance Selection:</h2>
 * <ul>
 * <li><b>Default Tolerance:</b> ε = max(m, n) * ||A||₂ * machine_epsilon</li>
 * <li><b>Custom Tolerance:</b> Users can specify a custom threshold for noise filtering</li>
 * </ul>
 *
 * <h2>Usage Example:</h2>
 * <pre>{@code
 * Matrix A = ...; // Singular matrix
 * double[] singularValues = new SVDecomposition().decompose(A).getSingularValues();
 *
 * // Estimate rank
 * int rank = RankEstimation.effectiveRank(singularValues);
 *
 * // Check for full rank
 * boolean isFullRank = (rank == Math.min(A.getRowCount(), A.getColumnCount()));
 * }</pre>
 *
 * <h2>Applications:</h2>
 * <ul>
 * <li>Detecting singular or ill-conditioned matrices</li>
 * <li>Determining the dimension of the null space (Nullity = n - Rank)</li>
 * <li>Subspace intersection and basis construction</li>
 * </ul>
 *
 * @author JLC Development Team
 * @version 1.0
 * @since 1.0
 * @see SVDecomposition
 * @see net.faulj.condition.ConditionNumber
 */
public class RankEstimation {
	public RankEstimation() {
		throw new RuntimeException("Class unfinished");
	}
}